# Initializing a Tensor

In [ ]:
import torch
import numpy as np

# https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html
# Tensors are similiar to NumPy's ndarray, except tensors can run on GPUs or other hardware accelerators
# We can initialize these in a couple of different ways..

# 1. Directly from data
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

# 2. Via a NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# 3. From another tensor
#    the new tensor will retain the properties (shape, datatype) of the arguements tensor, unless explicitly overridden
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")


# 4. With random or constant values
#    shape: Is a tuple of tensor dimensions, determines dimensionality of the output tensor
shape = (2,3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8532, 0.9051],
        [0.6545, 0.2752]]) 

Random Tensor: 
 tensor([[0.0895, 0.7514, 0.5171],
        [0.8839, 0.5862, 0.4509]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attributes of a Tensor

In [14]:
# Tensor attributes describe their shape, datatype, and the device, on which they are stored
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operation on a Tensor

In [18]:
# By pyTorch we have over 100 tensor operations, such as arithmetic, linear algebra, matrix multipication, sampling and more!
# We can run this code using a GPU, by the `.to` method

# If GPU available this should work...
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

# Joining Tensors
# `torch.cat` can be used to concatenate a sequence of tensors along a given dimension
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


# Arithmetic Operations

In [19]:
# Matrix Multipication between two tensors
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

# Single Element Tensor

In [20]:
# If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you
# can convert it to a Python numerical value using item()

agg = tensor.sum()
agg_item = agg.item()
print(agg.item, type(agg_item))

<built-in method item of Tensor object at 0x000001DF2FE14D70> <class 'float'>
